package:
  name: "fastfetch"
  version: "2.52.0"
  type: "binary"
  architecture: "aarch64"
  description: "Fast system information tool"
  maintainer: "APGer <anmitali198@gmail.com>"
  license: "MIT"
  homepage: "https://github.com/fastfetch-cli/fastfetch"
  tags: ["system", "info", "cli", "neofetch", "nuros"]
  dependencies: ["libvulkan1", "libwayland-client0", "libxcb-randr0", "libxrandr2", "libdbus-1-3", "libpci3", "libdrm2", "libpulse0"]
  conflicts: []
  provides: []
  replaces: []
  conf: []
source:
  url: "https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/{{VERSION}}.tar.gz"
build:
  dependencies: ["build-essential", "cmake", "gcc-aarch64-linux-gnu", "g++-aarch64-linux-gnu"]
  script: |
    mkdir build
    cd build
    cmake .. \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release \
      -DENABLE_SYSTEM_YYJSON=OFF \
      -DCMAKE_SYSTEM_NAME=Linux \
      -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
      -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
      -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
    make -j$(nproc)
    cd ..
install:
  script: "cd build && make DESTDIR=\"$DESTDIR\" install"
